#pragma once

using eWM_DragDataType = enum eWM_DragDataType
{
    WM_DRAG_ID,
    WM_DRAG_ASSET,
    WM_DRAG_ASSET_LIST,
    WM_DRAG_RNA,
    WM_DRAG_PATH,
    WM_DRAG_NAME,
    WM_DRAG_VALUE,
    WM_DRAG_COLOR,
    WM_DRAG_DATASTACK,
    WM_DRAG_ASSET_CATALOG,
    WM_DRAG_GREASE_PENCIL_LAYER,
};
